import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <head>
        <title>Flexx App TS</title>
        <meta name='description' content='Generated by flexx'/>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <main>
        <h1 className='text-3xl font-bold underline'>Hello flexx</h1>
      </main>

    </div>
  )
}
